protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
		$criteria = new CDbCriteria();
		$count = Game::model()->count($criteria);
		$pages = new CPagination($count);
		$pages->pageSize = '12';
		$pages->applyLimit($criteria);
		$gameList = Game::model()->findAll($criteria);

		$this->render('index', array('gameList'=>$gameList, 'pages'=>$pages));
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$modelUser = Users::model()->findByPk(Yii::app()->user->id);
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-Type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_SUCCESS, AlertMess::FEEDBACK_SUCCESS);
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model,'modelUser'=>$modelUser));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		if (!Yii::app()->user->isGuest) {
			Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_DANGER, AlertMess::ALREADY_AUTH);
			$this->redirect(array('site/index'));
		}

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo TbActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	public function actionReg() {
		$model = new Users;
		$modelMyUsers = Users::model()->findByPk(Yii::app()->user->id);
		$model->scenario = 'reg';

		if(isset($_POST['ajax']) && $_POST['ajax']==='users-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		if (!Yii::app()->user->isGuest) {
			Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_DANGER, AlertMess::ALREADY_REG);
			$this->redirect(array('site/index'));
		}

		if(isset($_POST['Users'])) {
			$model->attributes = $_POST['Users'];
			$model->curr = 1000;
			if ($model->save()) {
				Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_SUCCESS, AlertMess::SUCCESS_REG);
				$this->redirect(array('site/index'));
			}
		}
		$this->render('reg', array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		$userOffline = Users::model()->findByPk(Yii::app()->user->id);
		$userOffline->online = 0;
		$userOffline->date_last = time();
		$userOffline->save();
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}

	public function actionPage($view) {
		$textPageCont = Text::model()->findAll('path=:path', array('path'=>'/site/page?view=about'));
		foreach($textPageCont as $value) {
			$textPageArr[$value->id] = $value->full_text;
			$textPageArrTitl[$value->id] = $value->name;
		}
		$this->render('pages/about', array('textPageArr'=>$textPageArr, 'textPageArrTitl'=>$textPageArrTitl));
	}

	public function actionDebug() {
		echo "<center><h1>NULL</h1></center>";
	}
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="language" content="ru">
	<?php Yii::app()->bootstrap->register(); ?>
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo Yii::app()->request->baseUrl; ?>/css/favicon.ico">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/myStyle.css">

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/script.js"></script>
</head>

<body>
<div class="container" id="page">
<?php
if (WorkView::countCustomServer(INTEGER_PRINT) >= 1 && $this->myInfoNick == 'admin') {
	$topLinkBar = array(
			'label' => 'Топ игровых серверов '.WorkView::countCustomServer(),
			'encodeLabel'=>false,
			    'items' => array(
						    	array('label' => 'Список игровых серверов', 'url' => '/tgameServer/index'),
						    	array('label' => 'Модерация '.WorkView::countCustomServer(), 'url' => '/tgameServer/moder'),
							),
			    );
} else {
	$topLinkBar = array('label' => 'Топ игровых серверов', 'url' => '/tgameServer/index');
}
?>

<?if (!Yii::app()->user->isGuest) {
	$itemsLeftMenu = array(
		array('label' => 'Сообщения '.WorkView::countNewMail(), 'url' => '/mail/cabinet', 'type'=>'raw'),
		array(
			'label' => WorkView::countOrderGoodsRevie(),
			'encodeLabel'=>false,
		    'items' => array(
							array('label' => 'Заказы '.WorkView::countNewOrder(), 'url' => '/order/cabinet'),
							array('label' => 'Продажа '.WorkView::countNewGoods(), 'url' => '/goods/cabinet'),
							array('label' => 'Отзывы '.WorkView::countNewRevie(), 'url' => '/revie/index'),
						),
		),
		$topLinkBar,
		array(
			'label' => 'О сайте',
				'encodeLabel'=>false,
			    'items' => array(
			    				array('label' => 'Правила для продавцов', 'url' => '/goods/infoSaller'),
						    	array('label' => 'Контакты', 'url' => '/site/contact'),
								array('label' => 'Помощь', 'url' => '/site/page?view=about'),

							),
		),
);} else {
	$itemsLeftMenu = array(
		array('label' => 'Помощь', 'url' => '/site/page?view=about'),
		array('label' => 'Контакты', 'url' => '/site/contact'),
		array('label' => 'Топ игровых серверов', 'url' => '/tgameServer/index'),
);}?>
<?if (Yii::app()->user->isGuest) {
	$itemsAuth = array(
		array('label' => 'Войти', 'url' => '/site/login'),
		array('label' => 'Зарегистрироваться', 'url' => '/site/reg'),
	);
} else if (Yii::app()->user->name == 'admin') {
	$itemsAuth = array(
		array('label' => Yii::app()->user->name, 'url' => '/users/cabinet'),
		array('label' => 'Панель управления', 'url' => '/backend', 'id'=>'adm-site'),
		array('label' => "<span class='glyphicon glyphicon-log-out'></span>", 'url' => '/site/logout', 'type'=>'raw'),
	);
} else {
	$itemsAuth = array(
		array('label' => Yii::app()->user->name, 'url' => '/users/cabinet'),
		array('label' => "<span class='glyphicon glyphicon-log-out'></span>", 'url' => '/site/logout', 'type'=>'raw'),
	);
}?>
	<div id="header">
		<?php $this->widget('bootstrap.widgets.TbNavbar', array(
		    'brandLabel' => Yii::app()->name,
		    'htmlOptions' => array('style'=>'border-radius:0px;'),
		    'display' => null, // default is static to top
		    'collapse' => true,
		    'items' => array(
		        array(
		        	'encodeLabel'=>false,
		            'class' => 'bootstrap.widgets.TbNav',
		            'items' => $itemsLeftMenu,
		        ),
		        array(
		            'class' => 'bootstrap.widgets.TbNav',
		            'encodeLabel'=>false,
		            'htmlOptions' => array('class'=>'navbar-right'),
		            'items' => $itemsAuth,
		        ),
		    ),
		)); ?>
	</div><!-- header -->

	<?if (!Yii::app()->user->isGuest):?>
	<div class="container">
		<div class="alert alert-warning in alert-block fade">
			<table class="chip-offers" style="width:100%;">
				<tr>
					<th class="text-left">На вашем счету: <?=WorkView::myCurren()?>
					<a style="margin-left:20px;text-decoration:none;" href="<?=$this->createUrl('users/fillUpPurse')?>">Пополнить счет?</a>
					<a style="margin-left:20px;text-decoration:none;" href="<?=$this->createUrl('users/fillDownPurse')?>">Вывести средства</a></th>
					<th class="text-right">Денег в <a href="<?=$this->createUrl('order/cabinet')?>">корзине</a>: <?=WorkView::myCurrenBasket()?></th>
				</tr>
			</table>
		</div>
	</div>
	<?endif?>

	<?$textPageCont = WorkView::textPage('/');
	foreach($textPageCont as $value) {
		$textPageArr[$value->id] = $value->full_text;
	}?>

	<div id="content" class="container main-container content-chips content-chips-promo">

		<!-- # path='/' && id='1' # -->
		<div class='text-block callout callout-info'>
			<p>
				<?=$textPageArr['1']?>
			</p>
		</div>
		<!-- END # path='/' && id='1' # END -->

		<?php echo $content; ?>

		<div class="clear"></div>

	</div>

	<footer class="main-footer">
		<div class="container">
		    <ul class="right">
		    	<li>© <?=date('Y')?> GameVal</li>
		    	<li>Обратная связь: <a href="mailto:vityachis@ya.ru">vityachis@ya.ru</a></li>
		    </ul>
		</div>
	</footer>

</div><!-- page -->

</body>
</html>